In [0]:
import numpy as np

創建陣列

In [0]:
np1 = np.array([1, 2, 3])
np2 = np.array([3, 4, 5])

ndarray 的關鍵屬性

In [3]:
print(np1.ndim, np1.shape, np1.dtype) 

1 (3,) int64


In [5]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [6]:
type(x)

numpy.ndarray

In [7]:
x.shape

(2, 3)

In [8]:
x.dtype

dtype('int32')

使用numpy.arange() 創建陣列

In [9]:
#numpy.arange(start, stop, step, dtype)

x = np.arange(5) 
x

array([0, 1, 2, 3, 4])

In [11]:
x = np.arange(7, dtype =  float)
x

array([0., 1., 2., 3., 4., 5., 6.])

使用numpy.linspace創建等差數列

In [12]:
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [13]:
a = np.linspace(1,1,10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
a = np.linspace(10, 20, 5, endpoint = False)  
print(a)

[10. 12. 14. 16. 18.]


In [15]:
a = np.linspace(10, 20, 5)  
print(a)

[10.  12.5 15.  17.5 20. ]


In [16]:
a = np.linspace(10, 20, 5, endpoint = True)  
print(a)

[10.  12.5 15.  17.5 20. ]


使用numpy.logspace 函數創建一個等比數列

In [17]:
a = np.logspace(0,9,10,base=2)
print (a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


reshape函數==>改變函數形狀

In [19]:
np3 = np.array([1, 2, 3, 4, 5, 6])
np3.shape

(6,)

In [21]:
np4 = np3.reshape([2, 3])
print(np4.ndim, np4.shape, np4.dtype)
np4

2 (2, 3) int64


array([[1, 2, 3],
       [4, 5, 6]])

陣列形狀操控：壓平與轉置

In [22]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [23]:
ar.T

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

In [24]:
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [25]:
ar2=np.array([np.arange(1,6),np.arange(10,15)]); 
ar2.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

改變陣列型別（bool、int、float、string）的運算

In [27]:
np5 = np3.astype('int32')
print(np3.dtype)
print(np5.dtype)

int64
int32


陣列索引與切片運算

In [28]:
np13 = np.array([1, 2, 3, 4, 5, 6])
print(np13[2])

3


In [30]:
np23 = np13.reshape([2, 3])
print(np23)
print(np23[1, 0])

[[1 2 3]
 [4 5 6]]
4


In [31]:
np3 = np.array([1, 2, 3, 4, 5, 6])
print(np3 > 3)
print(np3[np3 > 3])

[False False False  True  True  True]
[4 5 6]


In [32]:
# 陣列的切片運算:
np10 = np.arange(10)
s = slice(2,7,2)   # 從索引 2 開始到索引 7 停止，間隔為2
print (np10[s])

[2 4 6]


In [33]:
np10 = np.arange(10)  
np11 = np10 [2:7:2]   # 從索引 2 開始到索引 7 停止，間隔為 2
print(np11)

[2 4 6]


In [34]:
np10 = np.arange(10)  
np12 = np10 [2::2]  
print(np12)

[2 4 6 8]


In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
print (a[...,1])   
print (a[1,...])   
print (a[...,1:])

[2 5 8]
[4 5 6]
[[2 3]
 [5 6]
 [8 9]]


In [37]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); 
print(ar)
print(ar[1,2]) 
print(ar[2,:]) 
print(ar[:,1]) 
print(ar[2,-1]) 

[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]
7
[11 12 13]
[ 3  8 12]
13


In [38]:
ar=2*np.arange(6)
ar

array([ 0,  2,  4,  6,  8, 10])

In [39]:
print(ar[1:5:2])
print(ar[1:6:2])
print(ar[:4])
print(ar[4:]) 
print(ar[::3])

[2 6]
[ 2  6 10]
[0 2 4 6]
[ 8 10]
[0 6]


In [40]:
ar[:3]=1
ar

array([ 1,  1,  1,  6,  8, 10])

In [4]:
ar=2*np.arange(6)
ar[2:]=np.ones(4)
ar

array([0, 2, 1, 1, 1, 1])

依據axis的運算

In [5]:
np3 = np.array([1, 2, 3, 4, 5, 6])
np3 = np3.reshape([2, 3])
print(np3)
print(np3.sum(axis=1))
print(np3.sum(axis=0))

[[1 2 3]
 [4 5 6]]
[ 6 15]
[5 7 9]


Universal Functions

In [7]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [9]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
       3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23,
      

In [12]:
x = np.random.randn(5)
y = np.random.randn(5)
print(x)
print(y)
print(np.maximum(x, y))

[-0.08774457 -0.15598318  0.42903293  1.88680822 -1.34128855]
[ 0.38333411 -1.99922365  0.72787713  0.39092739  2.31582643]
[ 0.38333411 -0.15598318  0.72787713  1.88680822  2.31582643]
